site_name: Siddhi-IO-SQS
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
pages:
- Welcome to WSO2 Siddhi IO SQS: index.md
- API Docs:
  - 1.0.3: api/1.0.3.md
  - 1.0.2: api/1.0.2.md
  - 1.0.1: api/1.0.1.md
  - 1.0.0: api/1.0.0.md
  - ? ''
    : api/.md
  - latest: api/latest.md
- License: about/license.md
theme: material
